name: Bomberman
author: Cuuky
version: 1.0
main: de.cuuky.bomberman.Bomberman

commands:
    build:
       permission: bm.build
    setSpawn:
       permission: bm.setSpawn
    start:
       permission: bm.start
    setLobby:
       permission: bm.setLobby
    setLoc:
       permission: bm.setLoc
    rebuild:
       permission: bm.rebuild
    infinitetnt:
       aliases: [inf, infinite]
       permission: bm.infinite
    bomberman:
       aliases: bm
    vote: